- hosts: localhost
  gather_facts: no

  tasks:

  # =========================
  # Kubernetes (EKS Deploy)
  # =========================

  - name: Apply Kubernetes Deployment
    command: kubectl apply -f deployment.yaml

  - name: Apply Kubernetes Service
    command: kubectl apply -f service.yaml


  # =========================
  # SNS Setup (Email Alert)
  # =========================

  - name: Create SNS topic
    command: >
      aws sns create-topic
      --name ec2-alert-topic

  - name: Subscribe email to SNS topic
    command: >
      aws sns subscribe
      --topic-arn arn:aws:sns:us-east-1:548049827719:ec2-alert-topic
      --protocol email
      --notification-endpoint midowael.allam@gmail.com


  # =========================
  # EventBridge Rule
  # =========================

  - name: Create EventBridge rule for EC2 creation
    command: >
      aws events put-rule
      --name ec2-create-rule
      --event-pattern '{
        "source": ["aws.ec2"],
        "detail-type": ["EC2 Instance State-change Notification"],
        "detail": {
          "state": ["pending"]
        }
      }'
      --state ENABLED


  # =========================
  # EventBridge Target -> SNS
  # =========================

  - name: Attach SNS target to EventBridge rule
    command: >
      aws events put-targets
      --rule ec2-create-rule
      --targets "Id"="1","Arn"="arn:aws:sns:us-east-1:548049827719:ec2-alert-topic"
